const taskMatrix = {
  "charisma": [
    {"text": "Plant your feet flat, lock your posture straight, and execute a firm, silent nod to the next person you see. Zero double-blinking or shuffling tells allowed.", "label": "Presence", "rating": 4},
    {"text": "Stand tall before the nearest reflective surface, wink confidently at yourself, and point. Yes, it is cringy, but it shatters current serious thought loops.", "label": "Fun Factor", "rating": 5},
    {"text": "Look at the person nearest to you, identify a genuine structural detail they chose, and deliver a clean, crisp compliment without trailing drop-offs.", "label": "Charisma Boost", "rating": 4},
    {"text": "Speak your next three real-world sentences aloud with deliberate volume and deeper inflection. Drop all low-confidence vocal fillers.", "label": "Vocal Power", "rating": 3},
    {"text": "Sit perfectly still without adjusting your clothes, touching your hair, or glancing at your phone for 120 seconds. Command space through absolute stillness.", "label": "Presence", "rating": 5},
    {"text": "Unclench your jaw, soften your shoulders, and look straight ahead with a calm, unbothered expression. High status looks completely relaxed.", "label": "Poise", "rating": 4},
    {"text": "Imagine an invisible thread pulling the top of your head to the sky. Walk 10 steps with unhurried composure. Speed signals anxiety.", "label": "Status Frame", "rating": 3},
    {"text": "Look someone directly in the eyes for a full three seconds before speaking. Force your focus to remain entirely locked and steady.", "label": "Pain", "rating": 4},
    {"text": "Open your hands, relax your wrists, and maintain a completely open, non-defensive posture during your next interaction.", "label": "Charisma Boost", "rating": 3},
    {"text": "Deliver a sharp, clean nod of agreement when spoken to next. Eliminate frantic double-nodding tells completely.", "label": "Vocal Power", "rating": 4},
    {"text": "Sit up straight and let your hands rest openly on your desk or knees. Eliminate nervous physical tells from your baseline.", "label": "Presence", "rating": 4},
    {"text": "Say 'No' internally to three things you do not want to do today. Build internal boundaries to protect your focus.", "label": "Confidence", "rating": 5},
    {"text": "Take two deep breaths and lower your vocal pitch to the lowest register of your throat. Speak your next thought with deep weight.", "label": "Vocal Power", "rating": 3},
    {"text": "Widen your physical platform stance slightly. Notice how expanding your physical base instantly signals security to your neurology.", "label": "Status Frame", "rating": 4},
    {"text": "Keep your gaze perfectly level with the horizon as you walk forward. Look like someone who knows exactly where they are going.", "label": "Presence", "rating": 3},
    {"text": "Smooth out your breathing, lower your shoulders, and project absolute calm. The room naturally centers around the quietest presence.", "label": "Poise", "rating": 5},
    {"text": "Look around your current space and find three distinct design elements. Focus on each to anchor absolute situational presence.", "label": "Dopamine Hit", "rating": 3},
    {"text": "Practice delivering a clear, concise introduction of yourself aloud. Cut out any trailing, weak justifications.", "label": "Vocal Power", "rating": 4},
    {"text": "Open your palms, relax your shoulders, and smile gently. Project unshakeable comfort within your own skin.", "label": "Charisma Boost", "rating": 5},
    {"text": "Stand tall, pull your shoulder blades gently together, and hold for 10 seconds. Correct your desktop slouch instantly.", "label": "Productivity", "rating": 3},
    {"text": "Plant both feet flat on the floor and feel your weight pull down. Anchor your mind completely into the physical coordinates of the room.", "label": "Presence", "rating": 4},
    {"text": "Relax your facial expressions completely. Bring absolute clarity and neutral peace to your eyebrows and forehead.", "label": "Poise", "rating": 4},
    {"text": "Maintain a warm, subtle, completely unbothered smile for the next 60 seconds. Exude clean social intelligence.", "label": "Charisma Boost", "rating": 3},
    {"text": "Execute a slow, controlled physical gesture with your right hand as you explain your next choice. Cultivate graceful authority.", "label": "Status Frame", "rating": 4},
    {"text": "Consciously drop your shoulders away from your ears. Release the physical burden of chronic desktop tension right now.", "label": "Pain", "rating": 3},
    {"text": "Sit tall, open your chest, and keep your hands loose on your lap. Command authority through stillness.", "label": "Presence", "rating": 5},
    {"text": "Speak a single phrase of gratitude aloud with total clarity and clean vocal resonance.", "label": "Charisma Boost", "rating": 4},
    {"text": "Look cleanly from left to right without moving your shoulders. Maintain a calm, high-status observational field.", "label": "Status Frame", "rating": 3},
    {"text": "Take two deep breaths and feel your pulse settle. Command your own physiology before you try to command a room.", "label": "Poise", "rating": 4},
    {"text": "Uncross your arms, open your shoulders, and step forward into an open posture. Project safety and absolute strength.", "label": "Confidence", "rating": 4},
    {"text": "Rest your hands flat on a table or your knees. Avoid any tapping or fidgeting. Let your stillness command respect.", "label": "Presence", "rating": 5},
    {"text": "Practice stating a boundary clearly in your mind. Say no internally to unneeded demands with complete peace.", "label": "Confidence", "rating": 4},
    {"text": "Stand up and stretch your arms out wide to your sides. Hold this open posture to flood your system with confidence.", "label": "Fun Factor", "rating": 4},
    {"text": "Soften the expression around your eyes and mouth. Project an approachable, balanced, and deeply secure social presence.", "label": "Charisma Boost", "rating": 4},
    {"text": "Plant your feet firmly, lift your chest, and take a deep breath. Stand like an anchor that cannot be shaken.", "label": "Status Frame", "rating": 5},
    {"text": "Consciously slow down your rate of speech as you state your immediate goal aloud. Let every word carry clean weight.", "label": "Vocal Power", "rating": 4},
    {"text": "Rest your body comfortably back into your seat without slouching. Occupy your space with absolute confidence.", "label": "Presence", "rating": 3},
    {"text": "Take a deep breath, pull your belly button slightly in, and lengthen your spine. Instantly improve your physical presence.", "label": "Productivity", "rating": 3},
    {"text": "Practice a steady, clear handshake motion in the air with total focus and solid wrist tension.", "label": "Charisma Boost", "rating": 3},
    {"text": "Drop any lingering tension from your thighs and calves. Plant your feet securely and feel completely grounded in the room.", "label": "Poise", "rating": 4},
    {"text": "Lift your chin by a fraction of an inch, roll your shoulders back, and look around with quiet, observational power.", "label": "Status Frame", "rating": 4},
    {"text": "Take a long, deep breath into your stomach. Release it slowly to settle your pulse and step into absolute presence.", "label": "Poise", "rating": 4},
    {"text": "Practice speaking an entire sentence in one steady, continuous breath. Deliver your ideas smoothly without rushing.", "label": "Vocal Power", "rating": 3},
    {"text": "Stand up, roll your shoulders back, and balance your weight perfectly between both heels. Own your platform.", "label": "Presence", "rating": 4},
    {"text": "Take a deep breath, close your eyes, and listen to the furthest sound in the room. Sharpen your situational presence.", "label": "Presence", "rating": 5},
    {"text": "Keep your eyes perfectly level with the horizon as you stand straight. Look like someone who knows exactly where they are going.", "label": "Status Frame", "rating": 3},
    {"text": "Place your hands firmly on your desk or thighs. Breathe evenly and let your stillness anchor the room.", "label": "Poise", "rating": 4},
    {"text": "Practice speaking with a calm, melodic, unhurried cadence. Command attention by refusing to rush your words.", "label": "Vocal Power", "rating": 5},
    {"text": "Straighten your posture and take a single step forward with absolute intention. Commit fully to your space.", "label": "Confidence", "rating": 4},
    {"text": "Relax your hands completely. Let your fingers rest open and loose. Presence is born when nervous tension dies.", "label": "Presence", "rating": 4},
    {"text": "Lift your chest, lower your shoulders, and exhale completely. Let your physical structural baseline project absolute readiness.", "label": "Status Frame", "rating": 4},
    {"text": "Lock your gaze onto a single point across the room and hold your focus steady. Build the intensity of a calm mind.", "label": "Poise", "rating": 5},
    {"text": "Uncross your legs, plant both feet flat on the floor, and lengthen your spine. Stay centered and fully present.", "label": "Presence", "rating": 3},
    {"text": "Take a deep breath and expand your ribcage. Hold it for a moment, then release it to settle into high presence.", "label": "Poise", "rating": 3},
    {"text": "Stand with absolute posture and balance an imaginary object on your head. Bring structural grace to your form.", "label": "Fun Factor", "rating": 3},
    {"text": "Maintain a clear, direct, and unblinking gaze for 30 seconds. Build unshakeable visual composure.", "label": "Pain", "rating": 4},
    {"text": "Rest your hands flat on your lap, sit tall, and breathe slowly through your nose. Radiate absolute poise.", "label": "Presence", "rating": 4},
    {"text": "Speak your current primary goal aloud with perfect clarity and total authority. Command your own direction.", "label": "Vocal Power", "rating": 4},
    {"text": "Roll your shoulders back, square your hips, and expand your posture. Occupy your physical space completely.", "label": "Status Frame", "rating": 4},
    {"text": "Soften your face and let a steady, calm expression settle in. Look completely comfortable in the present moment.", "label": "Poise", "rating": 4},
    {"text": "Stand up tall, lift your chin, and take one full breath. Step directly into your personal power.", "label": "Confidence", "rating": 5},
    {"text": "Relax your hands and arms. Keep your body language open and high-status. Project absolute comfort.", "label": "Charisma Boost", "rating": 4},
    {"text": "Take two deep breaths and feel your pulse settle. Command your physiology before you command the room.", "label": "Poise", "rating": 4},
    {"text": "Place both feet flat on the ground and feel your connection to the floor. Stay anchored, steady, and unmovable.", "label": "Presence", "rating": 4},
    {"text": "Roll your shoulders backward three times, then let them settle low. Instantly remove physical strain.", "label": "Productivity", "rating": 3},
    {"text": "Take a deep breath, smooth your hair or face, and let your hands rest completely still. Zero frantic movements.", "label": "Presence", "rating": 5},
    {"text": "Lengthen your posture and take a steady breath. Project unshakeable strength through a solid physical frame.", "label": "Status Frame", "rating": 4},
    {"text": "Practice stating your name aloud with absolute, clean confidence. Own the authority of your identity.", "label": "Vocal Power", "rating": 4},
    {"text": "Unclench your fists and let your hands open completely. Release control over details you cannot influence.", "label": "Poise", "rating": 3},
    {"text": "Lift your chest, lower your shoulders, and breathe deeply. Step directly into a high-status physical state.", "label": "Status Frame", "rating": 5},
    {"text": "Lock your gaze onto an object, clear your mind, and maintain focus for 60 seconds. Build solid composure.", "label": "Poise", "rating": 4},
    {"text": "Sit straight, ground both feet flat on the floor, and keep your hands unmoving. Command respect through stillness.", "label": "Presence", "rating": 5},
    {"text": "Deliver a warm, steady nod toward your reflection. Affirm your personal authority and self-respect.", "label": "Confidence", "rating": 4},
    {"text": "Lengthen your spine and drop your shoulders. Take a long, deep breath to anchor your presence cleanly.", "label": "Poise", "rating": 4},
    {"text": "Practice speaking an objective cleanly without using any upward inflections at the end of your sentences.", "label": "Vocal Power", "rating": 4},
    {"text": "Roll your shoulders back, square your frame, and let your body settle into an unshakeable alignment.", "label": "Status Frame", "rating": 4},
    {"text": "Take a slow breath, clear your expression, and hold a calm, neutral facial baseline. Project absolute poise.", "label": "Poise", "rating": 5},
    {"text": "Stand up straight, plant both feet firmly, and take one deep breath. Step fully into your personal power.", "label": "Confidence", "rating": 5},
    {"text": "Relax your hands completely on your knees. Rest in the strength of an unhurried, highly authoritative physical state.", "label": "Presence", "rating": 4},
    {"text": "Look into the nearest mirror and trace your features with your eyes without judging what you see. Pure anchoring.", "label": "Presence", "rating": 4},
    {"text": "Widen your stance by two inches right now. Feel how changing your physical footprint shifts your internal confidence.", "label": "Status Frame", "rating": 4},
    {"text": "Take a deep breath and project a single crisp 'Yes' aloud with absolute closure. Eliminate hesitant delivery.", "label": "Vocal Power", "rating": 3},
    {"text": "Place your fingers lightly on your sternum and lift your chest away from your belly button. Open your physical layout.", "label": "Productivity", "rating": 3},
    {"text": "Maintain absolute eye level tracking with the room for the next two minutes. Resist the pull to drop your gaze.", "label": "Presence", "rating": 5},
    {"text": "Gently rest your dominant hand flat on your chest. Breathe directly into your palm to master emotional self-regulation.", "label": "Poise", "rating": 4},
    {"text": "State a three-word objective aloud right now as if it is an absolute law. Build direct speech mapping.", "label": "Vocal Power", "rating": 5},
    {"text": "Square your shoulders perfectly with the wall in front of you. Project clean readiness to face your immediate target.", "label": "Status Frame", "rating": 4},
    {"text": "Soften the expression across your cheekbones and ears. Let your face reflect a deeply grounded state of authority.", "label": "Poise", "rating": 4},
    {"text": "Stand up, separate your feet, and nod slowly with complete finality. Own your space completely.", "label": "Presence", "rating": 5},
    {"text": "Let your arms hang naturally loose at your sides without crossing or hiding them. Project total spatial safety.", "label": "Charisma Boost", "rating": 4},
    {"text": "Inhale for four counts, hold for four, and exhale for four. Establish total physiological control over your heart rate.", "label": "Poise", "rating": 4},
    {"text": "Sit completely straight and drop your shoulders down an extra fraction. Anchor your skeletal framework.", "label": "Status Frame", "rating": 3},
    {"text": "Speak your immediate next step aloud with total finality. Cut out trailing justifications or descriptions.", "label": "Vocal Power", "rating": 4},
    {"text": "Unclench your left fist completely. Let your palm rest open and notice how physical release clears mental tension.", "label": "Poise", "rating": 3},
    {"text": "Lift your chest, lower your shoulder blades, and execute a slow deep breath. Step straight into command alignment.", "label": "Status Frame", "rating": 5},
    {"text": "Maintain absolute observational stillness for 60 seconds. Do not twitch, scratch, or shift your weight.", "label": "Presence", "rating": 5},
    {"text": "Plant your feet flat on the floor, open your posture, and let a calm clarity wash over your mind. Absolute presence.", "label": "Poise", "rating": 5},
    {"text": "Affirm your direct personal path aloud right now with total vocal support. Own your workspace authority.", "label": "Vocal Power", "rating": 4},
    {"text": "Roll your shoulders back once and stand tall. Let your body teach your mind exactly who is in control.", "label": "Confidence", "rating": 5},
    {"text": "Take a deep breath and let your expressions relax into pure neutral composure. Radiate absolute unbothered poise.", "label": "Poise", "rating": 5}
  ],
  "wealth": [
    {"text": "Open your primary bank dashboard right now, locate your highest unnecessary recurring subscription, and ruthlessly hit cancel.", "label": "Financial Win", "rating": 5},
    {"text": "Review your last five digital transaction history lines with zero emotional guilt. Build raw tactical awareness of your cash flow.", "label": "Productivity", "rating": 4},
    {"text": "Look around your desk space and spot one item you bought but never use. Acknowledge the wasted capital and reset your buying rules.", "label": "Pain", "rating": 4},
    {"text": "Calculate your absolute hourly economic worth. Next time you purchase a luxury item, weigh its price directly against your labor hours.", "label": "Financial Win", "rating": 3},
    {"text": "Move a tiny amount of cash—even just $5—directly into a separate protected savings vault right now. Build the baseline keeping habit.", "label": "Financial Win", "rating": 4},
    {"text": "Read one brief analytical update regarding macroeconomic trends or micro-investing mechanics. Build familiarity with capital tools.", "label": "Productivity", "rating": 3},
    {"text": "Pause for 10 seconds and isolate one ordinary problem people face daily that you could build a micro-solution for.", "label": "Dopamine Hit", "rating": 5},
    {"text": "Look at your immediate surroundings and list three assets you own that genuinely maintain value over time.", "label": "Financial Win", "rating": 3},
    {"text": "Check your current credit parameters or primary debt asset balance cleanly. Facing the real numbers shatters avoidance instantly.", "label": "Pain", "rating": 5},
    {"text": "Write down a single, non-negotiable financial target number you intend to capture by this exact date next year.", "label": "Confidence", "rating": 4},
    {"text": "Think of one specific skill you possess that someone would willingly pay $50 to learn. Value your capability as capital.", "label": "Charisma Boost", "rating": 4},
    {"text": "Open a text pad and write down your three largest structural monthly expenses. Control begins with objective tracking data.", "label": "Productivity", "rating": 4},
    {"text": "Commit to spending zero variable dollars for the next four hours. Take active authority over your immediate cash leakage.", "label": "Financial Win", "rating": 4},
    {"text": "Identify a mainstream consumer product you use daily and research who owns its parent company. Move from consumer to builder mindset.", "label": "Productivity", "rating": 3},
    {"text": "Write down one specific financial rule you routinely break. Acknowledge it cleanly and set an immediate protective boundary.", "label": "Pain", "rating": 4},
    {"text": "Log into your investment pool dashboard. Simply verify the asset distribution framework to maintain alignment with your wealth.", "label": "Financial Win", "rating": 3},
    {"text": "Look at an item near your desk and deduce its wholesale manufacturing cost versus retail markup. Understand margin flows.", "label": "Productivity", "rating": 4},
    {"text": "Isolate one software tool or digital asset you can purchase this month that directly saves future time or overhead.", "label": "Financial Win", "rating": 4},
    {"text": "Write down the name of one iconic investor whose capital accumulation strategies you respect. Read one rule from them.", "label": "Productivity", "rating": 3},
    {"text": "Calculate how many months of basic survival overhead you have currently insulated in raw cash reserves. Know your operational runway.", "label": "Pain", "rating": 4},
    {"text": "Take two minutes to review how compound interest scaling vectors work. Realize how small changes stack long-term.", "label": "Dopamine Hit", "rating": 3},
    {"text": "List two household items you buy frequently that can be bought in bulk right now to drop your unit costs.", "label": "Financial Win", "rating": 4},
    {"text": "Locate the exact app on your phone that tempts you to spend money impulsively. Hide it inside a deep folder right now.", "label": "Productivity", "rating": 4},
    {"text": "Write down your primary source of income and map out one low-effort side path to expand its current delivery scale.", "label": "Confidence", "rating": 4},
    {"text": "Review your investment auto-contribution profiles. Increase your recurring allocation by just 1% or $10 right now.", "label": "Financial Win", "rating": 5},
    {"text": "Spot an unneeded item in your space that can be sold on an online catalog right now for quick liquidity.", "label": "Financial Win", "rating": 4},
    {"text": "Write down three words describing your current emotional response to money. Bringing awareness to code breaks behavioral patterns.", "label": "Pain", "rating": 4},
    {"text": "Recall your last major financial misstep. Forgive the choice, extract the hard operational rule, and delete the emotional guilt.", "label": "Poise", "rating": 5},
    {"text": "Spend two minutes researching an index asset tracker or standard mutual framework. Familiarize yourself with investment vehicles.", "label": "Productivity", "rating": 3},
    {"text": "List three companies you built transactions with this week. Ask yourself how they optimize their net margins.", "label": "Productivity", "rating": 4},
    {"text": "Identify one micro-friction in your working schedule that is costing you cash or hours. Plan an immediate automation fix.", "label": "Productivity", "rating": 5},
    {"text": "Write down your absolute net worth milestone target for five years out. Let the scale of ambition organize your actions.", "label": "Confidence", "rating": 5},
    {"text": "Open your ledger file and input any un-logged expenses from the past 48 hours. Maintain absolute financial accountability.", "label": "Productivity", "rating": 4},
    {"text": "Isolate one recurring billing invoice (like mobile or web insurance) that can be negotiated down. Set a calendar reminder.", "label": "Financial Win", "rating": 4},
    {"text": "Write down your single deepest financial anxiety block. Bringing it to the surface lets you build an engineering defense.", "label": "Pain", "rating": 5},
    {"text": "List two alternative asset allocations you do not currently own but want to explore this fiscal quarter.", "label": "Productivity", "rating": 3},
    {"text": "Calculate the exact cost of your most common daily lifestyle luxury habit over a full year. Realize the scale of micro-leaks.", "label": "Pain", "rating": 4},
    {"text": "Write down a strategy to automate your structural billing cycles to eliminate late fee payment friction.", "label": "Productivity", "rating": 4},
    {"text": "Identify one foundational text on wealth architecture or asset distribution you will read next. Download a clean summary.", "label": "Productivity", "rating": 3},
    {"text": "Look at your calendar and locate one block of time you consistently waste. Re-label that block as your asset-building slot.", "label": "Productivity", "rating": 4},
    {"text": "Write down a micro-business solution concept that requires less than $100 to initialize. Train your building eye.", "label": "Dopamine Hit", "rating": 5},
    {"text": "Review your checking accounts for hidden administrative fees. Capital preservation starts with tracking minor parameters.", "label": "Financial Win", "rating": 3},
    {"text": "Think of an associate or network connection who handles capital with high efficiency. Plan one distinct question to ask them.", "label": "Charisma Boost", "rating": 4},
    {"text": "Write down the three specific asset choices you are happiest you made. Understand what winning investments feel like.", "label": "Confidence", "rating": 4},
    {"text": "Isolate one expanding market trend visible in your region right now. Think about how your skills map to that value pipeline.", "label": "Productivity", "rating": 4},
    {"text": "Set a firm spending limit boundary for your food allocation this week. Govern your consumption strictly.", "label": "Financial Win", "rating": 4},
    {"text": "Spend two minutes researching the core differences between tax-advantaged accounts and traditional cash structures.", "label": "Productivity", "rating": 3},
    {"text": "List three specific metrics you can optimize this month to increase your primary marketplace professional valuation.", "label": "Productivity", "rating": 4},
    {"text": "Look at your last financial printout statement and highlight the highest outflow item. Decide if it matches your core roadmap.", "label": "Pain", "rating": 4},
    {"text": "Write down a simple, direct strategy to eliminate your highest-interest debt line. Focus your resources on clearing it.", "label": "Financial Win", "rating": 5},
    {"text": "Identify one automatic digital tool that can handle a task you currently pay an external service to process.", "label": "Financial Win", "rating": 4},
    {"text": "Write down one firm allocation threshold limit you will never cross, regardless of current market hype or peer indicators.", "label": "Confidence", "rating": 4},
    {"text": "Verify your cash balances. Ensure your holding funds are sitting in a high-yield configuration rather than a zero-return slot.", "label": "Financial Win", "rating": 4},
    {"text": "Isolate an industry specific problem that consistently triggers frustration. Write a 2-sentence solution design concept.", "label": "Dopamine Hit", "rating": 4},
    {"text": "List three small lifestyle items you purchase that yield high satisfaction indexes but carry low overhead cost variables.", "label": "Financial Win", "rating": 3},
    {"text": "Write down your target retention cash number for this quarter. Give your daily adjustments a clear target.", "label": "Confidence", "rating": 4},
    {"text": "Identify one digital subscription account you preserve out of pure laziness or trailing guilt. Terminate the access right now.", "label": "Financial Win", "rating": 5},
    {"text": "Spend two minutes defining the precise structural parameters of your baseline target retirement profile.", "label": "Productivity", "rating": 3},
    {"text": "List your current clear tangible assets. Acknowledge your existing economic base with absolute analytical respect.", "label": "Confidence", "rating": 4},
    {"text": "Select an asset you intend to buy. Write down three lifestyle cutbacks that will explicitly fund that specific target.", "label": "Financial Win", "rating": 4},
    {"text": "Review your recurring payment card profiles. Ensure no old trailing test trials have quietly converted into leakage slots.", "label": "Financial Win", "rating": 4},
    {"text": "Write down a single-sentence personal manifesto regarding your generational wealth. Give your cash building an ethical anchor.", "label": "Confidence", "rating": 4},
    {"text": "Analyze a small local service company in your sector. Estimate their client volume and calculate their baseline net margins.", "label": "Productivity", "rating": 4},
    {"text": "List two marketplace capabilities that will spike in economic demand over the next 36 months due to software disruptions.", "label": "Productivity", "rating": 4},
    {"text": "Calculate the exact total parameters of your fixed monthly survival cost overhead. Know your absolute floor configuration.", "label": "Pain", "rating": 4},
    {"text": "Write down one asset allocation choice you made out of fear or market hype. Extract the warning rule and reset.", "label": "Pain", "rating": 4},
    {"text": "Open your bank app interface and set a custom alert notification triggered whenever your cash profile dips below a line.", "label": "Financial Win", "rating": 3},
    {"text": "Identify an item you buy frequently that can be substituted with a longer-lasting version to drop future replacements.", "label": "Financial Win", "rating": 4},
    {"text": "Write your personal operating strategy for unexpected windfall income. Establish a rule so unexpected capital goes directly into assets.", "label": "Confidence", "rating": 5},
    {"text": "Spend two minutes checking how asset gains parameters are handled in your location. Optimize your cash collection loops.", "label": "Productivity", "rating": 3},
    {"text": "List three asset structures that do not rely on your active physical clock to execute returns. Frame your future investments.", "label": "Financial Win", "rating": 4},
    {"text": "Write down your single absolute primary economic constraint right now. Define the wall clearly so you can design a solution.", "label": "Pain", "rating": 5},
    {"text": "Review your auto-save distribution allocations. Increase the daily or weekly execution speed by a minor fraction.", "label": "Financial Win", "rating": 4},
    {"text": "Isolate a brand whose product ecosystem you respect. Check their corporate capitalization framework to see how value scales.", "label": "Productivity", "rating": 3},
    {"text": "Write down one structural expense line you can cut this week with zero reduction to your core happiness index.", "label": "Financial Win", "rating": 4},
    {"text": "Identify an asset resource or capability you own that currently sits completely idle. Think of a path to leverage it.", "label": "Productivity", "rating": 4},
    {"text": "List three habit vectors that are quietly siphoning off your capital pool. Select one to intercept with a protective gate.", "label": "Pain", "rating": 4},
    {"text": "Write down an explicit economic target milestone you will celebrate when hit. Link wealth loops to direct confirmation.", "label": "Confidence", "rating": 4},
    {"text": "Spend two minutes reviewing the core mechanics of equity. Understand how owning pieces of systems scales far past hourly wages.", "label": "Productivity", "rating": 4},
    {"text": "Enforce a rule on a premium luxury item you want: You can only buy it once your asset yields cover its exact price.", "label": "Financial Win", "rating": 5},
    {"text": "Calculate your total asset-to-debt ratio balance cleanly. Track this metric closely to ensure your financial platform is expanding.", "label": "Productivity", "rating": 4},
    {"text": "Isolate a high-tier skill you intend to master. Calculate the exact overhead price of a training module or text to accelerate it.", "label": "Productivity", "rating": 3},
    {"text": "List two simple adjustments to streamline your personal bank architecture to make account verification completely effortless.", "label": "Financial Win", "rating": 4},
    {"text": "Write down your primary spending emotional trigger (boredom, stress, peer pressure). Create an immediate intercept rail.", "label": "Pain", "rating": 5},
    {"text": "Isolate a recurring corporate overhead billing parameter you can drop by shifting onto an annual framework layout.", "label": "Financial Win", "rating": 4},
    {"text": "Spend two minutes reading about asset portfolio diversification. Understand how a balanced platform insulates your core cash.", "label": "Productivity", "rating": 3},
    {"text": "Write down three specific long-term investments you commit to holding for the next ten years. Embed patient discipline.", "label": "Confidence", "rating": 4},
    {"text": "Verify your asset cash insulation containers. Ensure your emergency cash is securely separate from active transaction cards.", "label": "Financial Win", "rating": 4},
    {"text": "Identify a business model asset class that scales with near-zero marginal cost of duplication (digital files or subscriptions).", "label": "Productivity", "rating": 4},
    {"text": "Write down your target investment configuration total for the final day of this fiscal year. Lock your focus down.", "label": "Confidence", "rating": 5},
    {"text": "List three methods to repurpose or reuse items you currently own instead of initiating a new retail purchase cycle.", "label": "Financial Win", "rating": 3},
    {"text": "Write down one successful financial decision you executed recently. Re-anchor that feeling of complete economic control.", "label": "Confidence", "rating": 4},
    {"text": "Spend two minutes defining the exact parameters of a high-yield allocation index. Know where short-term cash belongs.", "label": "Productivity", "rating": 3},
    {"text": "Isolate a lifestyle luxury expense you keep purely to maintain appearances or impress external observers. Excise it completely.", "label": "Financial Win", "rating": 5},
    {"text": "Write your explicitly mapped funding protocol for your next major life transition step. Prevent sudden cash drainage loops.", "label": "Productivity", "rating": 4},
    {"text": "List two system-level metrics you can inspect daily to track your clear economic health index without dashboard confusion.", "label": "Financial Win", "rating": 4},
    {"text": "Identify a micro-niche service offer you can build online using your core software competency framework.", "label": "Productivity", "rating": 4},
    {"text": "Write down the exact reason why building sovereign wealth matters to your legacy path. Link money back to core ethics.", "label": "Confidence", "rating": 5},
    {"text": "Spend two minutes tracking how systemic asset inflation eats unallocated cash values. Realize why money must stay moving.", "label": "Productivity", "rating": 3},
    {"text": "Open your ledger file, confirm your parameters exactly match your physical records, and close the sheet with pride.", "label": "Productivity", "rating": 4}
  ],
  "dopamine": [
    {"text": "Invert your device face down right now, clear your mind completely, and take 5 slow abdominal breaths. Break the cycle.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Walk directly to the nearest window and lock your gaze on the absolute furthest physical object on the horizon line for 60 seconds.", "label": "Presence", "rating": 3},
    {"text": "Turn your device screen away, set your posture straight, and do absolutely nothing for 120 seconds. Force receptor recalibration.", "label": "Pain", "rating": 5},
    {"text": "Drink a full glass of cold water deliberately. Focus entirely on the immediate physical cooling sensation inside your body.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Gently massage your temples and jaw alignment frame for 60 seconds. Release the deep hidden stress of digital eye lock.", "label": "Poise", "rating": 4},
    {"text": "Execute 10 steady bodyweight squats right now. Substitute toxic digital stimulation with a rapid biological rush.", "label": "Productivity", "rating": 4},
    {"text": "Step away from your workstation chair and perform a full, continuous physical stretch sequence. Break the sedentary loop.", "label": "Presence", "rating": 3},
    {"text": "Ruthlessly close every single open tab inside your active browser layout right now. Clear away your working visual clutter.", "label": "Productivity", "rating": 5},
    {"text": "Store your phone inside a deep drawer or separate room for the next 15 minutes. Build physical friction to kill impulse tells.", "label": "Pain", "rating": 4},
    {"text": "Close your eyes completely and separate the physical ambient sounds inside your immediate workspace coordinates.", "label": "Presence", "rating": 4},
    {"text": "Clean your primary device screen until it is immaculate. Restoring surface order yields an immediate hit of workspace clarity.", "label": "Dopamine Hit", "rating": 3},
    {"text": "Take three deep breaths, forcing your exhale loop to last twice as long as the inhale step. Instantly lower your pulse.", "label": "Poise", "rating": 4},
    {"text": "Step outside or lean out a window to capture direct natural sunlight across your face. Reset your biological clock parameters.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Sit tall, lock your fingers together, and stretch your hands completely high above your head. Hold for three counts.", "label": "Productivity", "rating": 3},
    {"text": "De-clutter your home screen setup layout. Delete every toxic, bright notification badge that hijacks your attention loop.", "label": "Productivity", "rating": 5},
    {"text": "Stand up and shake out your arms and wrists vigorously for 30 seconds. Release the pent-up tension of long digital blocks.", "label": "Fun Factor", "rating": 4},
    {"text": "Isolate three blue elements inside your immediate room coordinates. Simply identify them to shift out of internal mental text loops.", "label": "Presence", "rating": 3},
    {"text": "Write down your absolute primary priority target milestone for the rest of the day on physical paper. Lock it down.", "label": "Productivity", "rating": 4},
    {"text": "Close your eyes and trace the explicit physical warmth of your breath entering and leaving your lips. Rest inside reality.", "label": "Presence", "rating": 4},
    {"text": "Clear any random papers, cups, or trash off your active desk workspace area. Physical order initializes mental focus.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Take a slow deep breath, hold the air at the top for four full counts, then release it slowly. Drop the static index.", "label": "Poise", "rating": 4},
    {"text": "Execute 5 slow, controlled physical lunges on each side. Generate stable systemic energy to replace digital lethargy.", "label": "Productivity", "rating": 4},
    {"text": "Set your device screen parameters to complete grayscale mode right now. Stripping color completely kills the addictive pull of feeds.", "label": "Pain", "rating": 5},
    {"text": "Stand tall and execute a deep forward fold. Let your hands hang loose to bring rapid fresh circulation to your brain.", "label": "Fun Factor", "rating": 4},
    {"text": "Close your eyes and visualize your primary operational target for tomorrow achieved. Align drive back with real outcomes.", "label": "Confidence", "rating": 4},
    {"text": "Consciously release any tension around your eyebrows, eyes, and jawline. Dissolve digital screen strain instantly.", "label": "Poise", "rating": 4},
    {"text": "Take a glass of cold water and consume it in slow, highly deliberate sips. Anchor focus inside tactile reality.", "label": "Presence", "rating": 4},
    {"text": "Clear out any stale, old notification arrays waiting inside your status dropdown list. Shield your attention space.", "label": "Productivity", "rating": 3},
    {"text": "Stand up and roll your neck in a slow, precise circular path three times in each direction. Clear structural strain.", "label": "Productivity", "rating": 3},
    {"text": "Activate an instrumental track, close your eyes, and follow the music layer with total focus until the countdown hits zero.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Write down the single task siphoning off your focus today. Physically cross it out to communicate an absolute boundary line to your brain.", "label": "Productivity", "rating": 4},
    {"text": "Sit perfectly tall and track the exact physical weight of your posture resting down on your seat. Be completely here.", "label": "Presence", "rating": 4},
    {"text": "Execute 10 slow, rhythmic shoulder rolls backward to reverse the physical compression of keyboard or screen locking.", "label": "Productivity", "rating": 3},
    {"text": "Turn off every non-human notification parameter toggle on your phone configuration right now. Take absolute command of your window.", "label": "Confidence", "rating": 5},
    {"text": "Take three deep breaths and consciously forgive yourself for any unallocated time blocks today. Reset focus cleanly right now.", "label": "Poise", "rating": 5},
    {"text": "Step away from your electronics array completely and walk around your room layout with total situational awareness.", "label": "Presence", "rating": 4},
    {"text": "Inhale into your chest cavity, expanding your lungs to their absolute capacity parameters. Hold, then dump the air fully.", "label": "Poise", "rating": 4},
    {"text": "Wipe down your primary desk surface. Increasing environmental layout clarity drops subconscious tracking stress variables.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Sit in absolute stillness and locate the exact physical sensation of your pulse inside your wrist. Re-connect physically.", "label": "Presence", "rating": 4},
    {"text": "Write down three clear physical capabilities you are genuinely grateful for possessing. Build clean, internal self-regard.", "label": "Charisma Boost", "rating": 4},
    {"text": "Stand up and execute a gentle spinal twist from side to side, letting your hands swing completely loose. Undo desk locking.", "label": "Fun Factor", "rating": 3},
    {"text": "Shut your phone completely off for the next ten minutes. Experience the absolute liberation of being entirely unreachable.", "label": "Pain", "rating": 5},
    {"text": "Consciously loosen your stomach muscles and drop into long deep diaphragmatic breathing. Clear out internal nervous compression.", "label": "Poise", "rating": 4},
    {"text": "Lock your focus onto a plant or out at a real tree for 60 seconds. Natural spatial geometry settles an overstimulated brain.", "label": "Presence", "rating": 4},
    {"text": "Write down one creative project you intend to build next. Route your dopamine into structural creation, not passive ingestion.", "label": "Confidence", "rating": 5},
    {"text": "Sit tall, pull your shoulder blades gently down, and hold for 10 seconds. Correct your alignment base instantly.", "label": "Productivity", "rating": 3},
    {"text": "Take a deep breath and state your current exact emotional state aloud with zero judgment. Labeling the metric defuses it.", "label": "Poise", "rating": 4},
    {"text": "Spend two minutes sketching a completely random geometric pattern on physical paper. Engage your spatial processing channels.", "label": "Fun Factor", "rating": 4},
    {"text": "Close your eyes and recall a memory where you had total, unshakeable control over your direction. Anchor that neural frame.", "label": "Confidence", "rating": 4},
    {"text": "Unsubscribe from the very last commercial marketing list item that hit your email account. Protect your attention capital.", "label": "Financial Win", "rating": 4},
    {"text": "Stand up, stretch your calf muscles thoroughly, and take a long breath. Inject real circulation down into your base.", "label": "Productivity", "rating": 3},
    {"text": "Set a firm, non-negotiable curfew cutoff boundary for your screen interactive loops tonight. Decide the exact hour right now.", "label": "Confidence", "rating": 4},
    {"text": "Close your eyes and narrow your attention down to capture the quietest audio frequency in the immediate room.", "label": "Presence", "rating": 4},
    {"text": "Take a full breath and twist your upper torso from side to side cleanly. Release hidden ribcage compression.", "label": "Productivity", "rating": 3},
    {"text": "Delete one shortcut app from your device that you haven't opened in the past month. Streamline your tool catalog.", "label": "Productivity", "rating": 4},
    {"text": "Sit back completely, close your eyes, and let your thoughts drift with zero direction for 60 seconds. Let your brain rest.", "label": "Poise", "rating": 4},
    {"text": "Execute 15 steady jumping jacks or alternating high steps right now. Flood your system with clean biological oxygen parameters.", "label": "Productivity", "rating": 4},
    {"text": "Wipe any accumulated dust layers off your computer monitors or keyboard keys. Elevate your environmental workspace standards.", "label": "Dopamine Hit", "rating": 3},
    {"text": "Take three deep breaths, focusing entirely on making your exhale phase silent and smooth. Calm your pulse.", "label": "Poise", "rating": 4},
    {"text": "Write down one macro-capability you want to master this season. Keep your mind locked on long-term trajectory targets.", "label": "Confidence", "rating": 4},
    {"text": "Stand tall, interlock your hands behind your back, and squeeze your shoulders to open your chest. Reverse desktop compression.", "label": "Productivity", "rating": 3},
    {"text": "Look around your space and align three objects that are currently sitting skewed or out of coordinate. Restore local order.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Close your eyes and isolate the precise physical weight of your clothing resting on your skin. Re-anchor tactile reality.", "label": "Presence", "rating": 4},
    {"text": "Splash your face completely with ice-cold water. Instantly fire the mammalian dive reflex to drop structural anxiety states.", "label": "Pain", "rating": 4},
    {"text": "Write down your primary execution target for the next 60 minutes. Give your focus a clear track to follow.", "label": "Productivity", "rating": 5},
    {"text": "Sit up straight, elevate your chin, and take one full, massive breath. Re-assert absolute command over your immediate state.", "label": "Status Frame", "rating": 4},
    {"text": "Spend two minutes lengthening and stretching your wrists and forearms to reverse typing or texting stress.", "label": "Productivity", "rating": 3},
    {"text": "Close your eyes and select a memory of someone who brings stable, calm energy into your life. Absorb that baseline.", "label": "Poise", "rating": 4},
    {"text": "Take two deep breaths and track any positions of tight physical compression in your frame. Consciously breathe release there.", "label": "Poise", "rating": 4},
    {"text": "Clear any random unallocated layout shortcut icons off your desktop environment screen. Minimize visual noise fields.", "label": "Productivity", "rating": 4},
    {"text": "Stand up and execute a slow, controlled balance on one foot for 30 seconds per side. Engage your spatial mind entirely.", "label": "Fun Factor", "rating": 3},
    {"text": "Write down one personal boundary parameter you will clearly state to an associate this week. Protect your personal bandwidth.", "label": "Confidence", "rating": 5},
    {"text": "Close your eyes and execute a slow breath. Drop the internal urge to respond to any digital alerts waiting for you right now.", "label": "Poise", "rating": 5},
    {"text": "Spend two minutes organizing one single drawer or section of your desk. Small physical wins build high execution momentum.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Take a deep breath and stretch your lower back muscles with a slow, seated torso twist. Restore spinal ease.", "label": "Productivity", "rating": 3},
    {"text": "Identify one channel of digital argument or negative media you routinely open. Commit to bypassing the link completely today.", "label": "Confidence", "rating": 4},
    {"text": "Sit in quiet stillness and state 5 things you can see, 4 you can feel, and 3 you can hear. Ground your parameters.", "label": "Presence", "rating": 5},
    {"text": "Stand tall, face toward the sky, and pull a massive deep breath into your system. Re-oxygenate your brain completely.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Write down one high-value capability you want to master this year. Orient your focus around real milestones.", "label": "Confidence", "rating": 4},
    {"text": "Consciously smooth out the expression on your face. Let your feature layout look balanced, calm, and deeply secure.", "label": "Poise", "rating": 5},
    {"text": "Take a deep breath and purge any unneeded, stale screenshots out of your phone media gallery. Clear your digital workspace.", "label": "Productivity", "rating": 3},
    {"text": "Spend two minutes performing slow, conscious circles with your ankles to increase blood flow down into your base platform.", "label": "Productivity", "rating": 3},
    {"text": "Close your eyes and trace the physical sensation of the air column passing over your teeth as you exhale. Stay right here.", "label": "Presence", "rating": 4},
    {"text": "Write down the exact micro-task you will execute the absolute millisecond this turnaround timer hits zero. Lock it in.", "label": "Productivity", "rating": 5},
    {"text": "Stand up, hinge at your hips, reach for your toes, and hold for 30 seconds. Release hamstring compression lines.", "label": "Productivity", "rating": 3},
    {"text": "Turn the display screen of every device in your room completely black for two minutes. Experience un-digitized spatial reality.", "label": "Presence", "rating": 5},
    {"text": "Take a deep breath and let your shoulders drop as low as they can physically settle. Dissolve physical tension fields instantly.", "label": "Poise", "rating": 4},
    {"text": "Write down three precise words that capture the exact version of yourself you are constructing. Align with identity.", "label": "Confidence", "rating": 4},
    {"text": "Spend two minutes cleaning your camera lenses, phone sensors, or monitor glasses. Bring absolute clarity to your optics.", "label": "Dopamine Hit", "rating": 3},
    {"text": "Close your eyes and force your shoulders to drop an extra fraction with every single exhale step. Sink into physical peace.", "label": "Poise", "rating": 5},
    {"text": "Execute 10 controlled, alternating high-knee steps right now. Kickstart circulation to break open focus ruts.", "label": "Productivity", "rating": 4},
    {"text": "Write down one internal block or past mistake you need to explicitly forgive yourself for. Dump the emotional payload.", "label": "Confidence", "rating": 5},
    {"text": "Take a deep centering breath and feel your skeletal connection to your seat. You are completely safe and grounded.", "label": "Presence", "rating": 4},
    {"text": "Spend two minutes categorizing three loose configuration files on your cloud layout. Bring structural order to your parameters.", "label": "Productivity", "rating": 4},
    {"text": "Close your eyes and visualize a wave of cool, clear stillness settling through your brain from top to bottom. Reset.", "label": "Poise", "rating": 5},
    {"text": "Write down one strict rule to govern your morning attention window. Insulate your opening hour from digital inputs.", "label": "Confidence", "rating": 5},
    {"text": "Stand up straight, square your shoulders, and execute three massive power breaths. Re-anchor your physiological control loop.", "label": "Status Frame", "rating": 4},
    {"text": "Wipe down your primary phone case framework cleanly. Bring an absolute immaculate, professional order to your daily tools.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Take a deep breath, smooth your posture completely out, and let a calm clarity wash over your mind. You are completely reset.", "label": "Poise", "rating": 5}
  ],
  "overwhelm": [
    {"text": "Isolate the single largest project on your desk. Write down only the very first, 2-minute micro-step. Ignore the rest completely.", "label": "Productivity", "rating": 5},
    {"text": "Open your active task sheet and ruthlessly draw a line through three items that do not absolutely require execution today.", "label": "Financial Win", "rating": 4},
    {"text": "Close your eyes, clear your head, and drop the need to fix or resolve everything right now. Let the universe wait 120 seconds.", "label": "Poise", "rating": 5},
    {"text": "Write down the top three distinct items triggering mental static or anxiety inside your head right now on a piece of paper.", "label": "Pain", "rating": 4},
    {"text": "Pinpoint the precise task you have been avoiding out of performance fear. Commit to interacting with it for just 120 seconds.", "label": "Pain", "rating": 5},
    {"text": "Take three slow breaths. Remind your subconscious: You do not have to finish the full project today; you only have to start one step.", "label": "Poise", "rating": 4},
    {"text": "Remove everything off your immediate desk layout except the one specific tool required for your next action line.", "label": "Productivity", "rating": 4},
    {"text": "Close your eyes and slow your breathing cadence down until your heart rate drops. Focus is born from absolute physiological calm.", "label": "Poise", "rating": 5},
    {"text": "Write down a single, non-negotiable execution target for the next hour. Ignore every other trailing alert or email request completely.", "label": "Productivity", "rating": 5},
    {"text": "Identify one recurring source of administrative friction inside your routine. Schedule a simple 2-minute block to automate it later.", "label": "Productivity", "rating": 4},
    {"text": "Take a deep breath and accept that you cannot control external metrics today. Focus entirely on controlling your immediate execution.", "label": "Confidence", "rating": 4},
    {"text": "Write down the name of one associate you can delegate a small task to, or one task you can safely cut. Lighten your payload.", "label": "Financial Win", "rating": 4},
    {"text": "Close your eyes and visualize yourself navigating through your current workload with absolute, unhurried, royal composure.", "label": "Status Frame", "rating": 4},
    {"text": "Open your calendar file right now and block out a non-negotiable 30-minute window tomorrow for absolute quiet, uninterrupted execution.", "label": "Productivity", "rating": 4},
    {"text": "Identify the absolute smallest sub-task currently on your plate. Execute it right now to lock an immediate, clean momentum win.", "label": "Dopamine Hit", "rating": 5},
    {"text": "Write down your primary source of work anxiety in one clear sentence. Defining the obstacle immediately defuses its control loop.", "label": "Pain", "rating": 4},
    {"text": "Take two deep breaths and consciously release any tension in your forehead and jaw. Do not match mental overwhelm with physical strain.", "label": "Poise", "rating": 4},
    {"text": "Isolate one communication or email thread you are dreading answering. Draft a concise, 1-sentence response right now and send it.", "label": "Pain", "rating": 5},
    {"text": "Write down three distinct milestone wins you achieved this week. Give yourself authentic credit to silence performance anxiety.", "label": "Confidence", "rating": 4},
    {"text": "Close your eyes and listen to your breathing for 60 seconds. Remember that your peace is separate from your to-do list.", "label": "Presence", "rating": 4},
    {"text": "Clear every single notification badge off your workspace dashboards. Start with a clean slate to lower visual stress fields.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Write down the absolute worst-case scenario of the project you are avoiding. Realize that you are fully equipped to survive it.", "label": "Pain", "rating": 4},
    {"text": "Take a deep breath, step away from your desk, and roll your shoulders back. Re-assert physical presence over mental static.", "label": "Status Frame", "rating": 4},
    {"text": "Identify one operational boundary parameters line you routinely let people cross. Commit to protecting that line aggressively today.", "label": "Confidence", "rating": 5},
    {"text": "Write a list of the 5 most critical items on your plate, then draw a line through the bottom 3. Focus only on the top 2.", "label": "Productivity", "rating": 5},
    {"text": "Close your eyes and take 5 long, silent breaths. Let the frantic urgency of the day completely drain out of your system.", "label": "Poise", "rating": 5},
    {"text": "Isolate one recurring micro-task that drains your energy. Plan a clear path to either eliminate it or automate it completely.", "label": "Financial Win", "rating": 4},
    {"text": "Write down one area of your life where you are trying to be completely perfect. Lower the standard to 'excellent' right now.", "label": "Confidence", "rating": 4},
    {"text": "Take two deep breaths and feel your feet flat on the floor. Ground your attention in physical reality, not mental narratives.", "label": "Presence", "rating": 4},
    {"text": "Identify one calendar call or meeting on your schedule that can be cleanly replaced with a brief text or email update.", "label": "Financial Win", "rating": 4},
    {"text": "Write down the name of an associate who always keeps a cool, steady head under pressure. Commit to matching their execution style today.", "label": "Charisma Boost", "rating": 4},
    {"text": "Clear your desk of any dirty cups, old papers, or random electronics. A minimalist workspace instantly creates a minimalist mind.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Close your eyes and breathe into your stomach. Remind your system that you have survived intense days before and will survive this one.", "label": "Poise", "rating": 4},
    {"text": "Write down one task you can safely push to next week. Give your current schedule immediate structural breathing room.", "label": "Financial Win", "rating": 4},
    {"text": "Isolate the core question you need answered to move forward on a frozen project. Write that question down clearly right now.", "label": "Productivity", "rating": 4},
    {"text": "Take a deep breath and consciously drop your expectations of how perfectly today must go. Lean into flexible execution fields.", "label": "Poise", "rating": 4},
    {"text": "Write down three words that describe how you want to feel at the end of the day. Let that target guide your focus choices.", "label": "Confidence", "rating": 4},
    {"text": "Identify one digital folder or tool configuration that is a chaotic mess. Plan a 2-minute block to clean its parameters later.", "label": "Productivity", "rating": 4},
    {"text": "Close your eyes and trace the explicit baseline boundary of your physical body. Remember that you are an anchor, not the storm.", "label": "Presence", "rating": 4},
    {"text": "Write down one micro-habit that always helps you reset when stress peaks. Commit to executing it if pressure rises today.", "label": "Poise", "rating": 4},
    {"text": "Take two deep breaths and lower your voice by an octave as you state your immediate target aloud. Command your state.", "label": "Vocal Power", "rating": 4},
    {"text": "Isolate one administrative loop you are stuck in. Write down a 1-sentence workaround to bypass the system friction parameters.", "label": "Productivity", "rating": 4},
    {"text": "Write down your top priority for the next 30 minutes. Turn off all incoming text loops and execute with total intent.", "label": "Productivity", "rating": 5},
    {"text": "Break down your immediate target into three distinct 40-second actions. Execute the first one immediately.", "label": "Productivity", "rating": 5},
    {"text": "Close all active messaging windows for the next 15 minutes. Protect your attention from constant micro-interruptions.", "label": "Focus", "rating": 4},
    {"text": "Take a deep breath and write down the single highest-leverage task on your desk right now. Ignore everything else.", "label": "Productivity", "rating": 5},
    {"text": "Step away from your workstation, stretch your back, and take three slow, deep breaths. Reset your physical state.", "label": "Poise", "rating": 4},
    {"text": "Identify one decision you have been delaying. Make a firm choice right now based on available data.", "label": "Confidence", "rating": 5},
    {"text": "Clear your computer screen of any unnecessary windows. Focus exclusively on one document or application.", "label": "Focus", "rating": 4},
    {"text": "Write down two small wins you can achieve in the next 10 minutes. Build immediate momentum.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Take a full 60 seconds to sit in complete silence with your eyes closed. Allow your mental clutter to settle.", "label": "Poise", "rating": 5},
    {"text": "Review your to-do list and highlight the single item that will yield 80% of today's progress.", "label": "Productivity", "rating": 5},
    {"text": "Drop your shoulders, unclench your teeth, and take a long, slow exhale. Release physical manifestation of stress.", "label": "Poise", "rating": 4},
    {"text": "Pick the easiest 2-minute item on your list and finish it instantly. Clear it off your mental radar.", "label": "Dopamine Hit", "rating": 4},
    {"text": "Set a timer for 10 minutes and work continuously on your primary task without stopping.", "label": "Focus", "rating": 5},
    {"text": "Write down a single-sentence summary of your main objective today. Clarity eliminates hesitation.", "label": "Confidence", "rating": 4},
    {"text": "Turn your phone face down and move it out of arm's reach. Eliminate the impulse to check notifications.", "label": "Focus", "rating": 4},
    {"text": "Take two deep breaths and remind yourself that action creates momentum, not planning.", "label": "Confidence", "rating": 4},
    {"text": "Select one complex email thread and write a concise 2-sentence response. Send it immediately.", "label": "Productivity", "rating": 5},
    {"text": "Clean your desktop workspace by removing all random papers and coffee cups. Create visual breathing room.", "label": "Presence", "rating": 4},
    {"text": "List three things that are going right with your current project. Shift out of problem-focused thinking.", "label": "Confidence", "rating": 4},
    {"text": "Inhale deeply for 4 seconds, hold for 4 seconds, and exhale for 4 seconds. Calm your central nervous system.", "label": "Poise", "rating": 4},
    {"text": "Delegate or remove one minor task from today's schedule. Focus only on essential commitments.", "label": "Productivity", "rating": 4},
    {"text": "Write down the exact next step required to unblock your current project. Execute that step now.", "label": "Productivity", "rating": 5},
    {"text": "Stand up, stretch your legs, and drink a full glass of cold water. Rehydrate your system for focus.", "label": "Presence", "rating": 3},
    {"text": "Acknowledge one aspect of your work that is beyond your direct control. Let go of trying to force it.", "label": "Poise", "rating": 5},
    {"text": "Break an intimidating project down into five micro-steps. Cross off the first step right now.", "label": "Dopamine Hit", "rating": 5},
    {"text": "Take a 2-minute break to gaze out the window at the sky or trees. Give your eyes and mind a rest.", "label": "Presence", "rating": 4},
    {"text": "Write down your primary goal for tomorrow morning before finishing today's session.", "label": "Productivity", "rating": 4},
    {"text": "Identify one self-imposed deadline that is causing unnecessary stress. Extend it reasonably.", "label": "Poise", "rating": 4},
    {"text": "Spend 120 seconds focusing solely on your breath. Notice the cool air entering your nose and warm air leaving.", "label": "Presence", "rating": 4},
    {"text": "Clean out your downloads folder or delete five unneeded files. Reclaim digital control.", "label": "Productivity", "rating": 3},
    {"text": "Remind yourself that done is better than perfect. Lower the threshold and ship the work.", "label": "Confidence", "rating": 5},
    {"text": "Write down one positive feedback or praise you received recently. Reinforce your competence.", "label": "Confidence", "rating": 4},
    {"text": "Set a firm stop time for your work day today. Create a boundary that forces efficiency.", "label": "Productivity", "rating": 4},
    {"text": "Close 10 unused tabs in your browser right now. Reduce mental friction instantly.", "label": "Focus", "rating": 4},
    {"text": "Take three long breaths and relax your facial muscles completely. Unclench your forehead.", "label": "Poise", "rating": 4},
    {"text": "Identify one recurring task that can be standardized into a template or checklist.", "label": "Productivity", "rating": 4},
    {"text": "Mute all social media channels for the rest of the workday. Protect your cognitive energy.", "label": "Focus", "rating": 5},
    {"text": "Write down three things you are grateful for in your professional journey right now.", "label": "Confidence", "rating": 4},
    {"text": "Focus on executing the next 5 minutes of work with zero multitasking. Single-task completely.", "label": "Focus", "rating": 5},
    {"text": "Take a deep breath and tell yourself: 'I handle one thing at a time with calm precision.'", "label": "Poise", "rating": 4},
    {"text": "Spend 60 seconds organizing your physical note pad or digital sticky note board.", "label": "Productivity", "rating": 3},
    {"text": "Identify one source of negative friction in your workspace and fix it right now.", "label": "Productivity", "rating": 4},
    {"text": "Write down the key takeaway from a recent challenge you faced. Convert friction into wisdom.", "label": "Confidence", "rating": 4},
    {"text": "Sit up straight, roll your shoulders back, and smile gently. Shift your state physically.", "label": "Status Frame", "rating": 4},
    {"text": "Limit your current focus to the next 120 seconds. Nothing outside this window matters right now.", "label": "Focus", "rating": 5},
    {"text": "Review your weekly goals and align your next action directly with your top priority.", "label": "Productivity", "rating": 4},
    {"text": "Take two deep breaths and release any urgency. Unhurried execution is fast execution.", "label": "Poise", "rating": 5},
    {"text": "Write a quick thank-you note or message to a peer or collaborator. Express clean gratitude.", "label": "Charisma Boost", "rating": 4},
    {"text": "Pick up a physical pen and notepad to plan your next action. Step away from digital screens.", "label": "Presence", "rating": 4},
    {"text": "Clear off your physical desk workspace until only your essential working tool remains.", "label": "Focus", "rating": 4},
    {"text": "Inhale deeply, hold for 3 seconds, and exhale completely. Feel the tension leave your chest.", "label": "Poise", "rating": 4},
    {"text": "Identify the smallest part of an intimidating task and complete it in under 60 seconds.", "label": "Dopamine Hit", "rating": 5},
    {"text": "Set your chat status to 'Do Not Disturb' while completing your current high-priority item.", "label": "Focus", "rating": 4},
    {"text": "Reflect on a past obstacle you successfully overcame. Remind yourself of your resilience.", "label": "Confidence", "rating": 5},
    {"text": "Take a moment to clean your mouse and keyboard surface. A pristine setup fosters focus.", "label": "Presence", "rating": 3},
    {"text": "Write down one lesson learned from a recent mistake without judging yourself.", "label": "Poise", "rating": 4},
    {"text": "Commit to 120 seconds of uninterrupted execution on your toughest challenge right now.", "label": "Productivity", "rating": 5},
    {"text": "Take a deep breath, smile, and acknowledge your progress today. Focus reclaimed.", "label": "Victory", "rating": 5}
  ]
};

export default taskMatrix;
